# Generated by Django 5.0.3 on 2024-04-10 21:31

import django.db.models.deletion
import FaceRecoApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecoApp', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=400)),
                ('cycle', models.CharField(choices=[('prepa', 'preparatory cycle'), ('engineer', 'engineering cycle')], max_length=20)),
                ('cycle_prepa', models.CharField(choices=[('1', '1 year '), ('2', '2 years')], max_length=20)),
                ('cycle_eng', models.CharField(choices=[('1', '1 year '), ('2', '2 years'), ('3', '3 years')], max_length=20)),
                ('filiere', models.CharField(choices=[('GM', 'genie mecanique'), ('GEM', 'genie electromecanique'), ('IAGI', 'genie informatique'), ('GI', 'genie indistruelle'), ('MSEI', 'genie electrique')], max_length=20)),
                ('image', models.ImageField(upload_to=FaceRecoApp.models.upload_location)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
        migrations.CreateModel(
            name='FaceRecognizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binary_steam', models.BinaryField()),
                ('student_class', models.ForeignKey(db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='FaceRecoApp.class')),
            ],
            options={
                'db_table': 'FaceRecoApp',
            },
        ),
    ]
