# Generated by Django 5.0.3 on 2024-04-11 20:03

import FaceRecoApp.models
from django.db import migrations, models

import FaceRecoApp.DetectorMain.utils


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecoApp', '0003_utilsdata_alter_contact_table_facerecognizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilsdata',
            name='cycle',
            field=models.CharField(choices=[('prepa', 'preparatory cycle'), ('engineer', 'engineering cycle')], max_length=80),
        ),
        migrations.AlterField(
            model_name='utilsdata',
            name='cycle_eng',
            field=models.CharField(blank=True, choices=[('1', '1 year '), ('2', '2 years'), ('3', '3 years')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='utilsdata',
            name='cycle_prepa',
            field=models.CharField(blank=True, choices=[('1', '1 year '), ('2', '2 years')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='utilsdata',
            name='filiere',
            field=models.CharField(blank=True, choices=[('GM', 'genie mecanique'), ('GEM', 'genie electromecanique'), ('IAGI', 'genie informatique'), ('GI', 'genie indistruelle'), ('MSEI', 'genie electrique')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='utilsdata',
            name='image',
            field=models.FileField(upload_to=FaceRecoApp.models.upload_location),
        ),
    ]
