# Generated by Django 5.0.3 on 2024-04-11 20:16

import FaceRecoApp.models
from django.db import migrations, models

import FaceRecoApp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecoApp', '0004_alter_utilsdata_cycle_alter_utilsdata_cycle_eng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilsdata',
            name='section',
            field=models.CharField(blank=True, choices=[(None, ''), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], db_column='section', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='utilsdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='creation_date'),
        ),
        migrations.AlterField(
            model_name='utilsdata',
            name='cycle',
            field=models.CharField(choices=[('cp', 'Preparatory Cycle'), ('ci', 'Engineering Cycle')], db_column='cycle', max_length=80),
        ),
        migrations.AlterField(
            model_name='utilsdata',
            name='cycle_eng',
            field=models.CharField(blank=True, choices=[(None, ''), ('1', '1 year'), ('2', '2 years'), ('3', '3 years')], db_column='cycle_eng', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='utilsdata',
            name='cycle_prepa',
            field=models.CharField(blank=True, choices=[(None, ''), ('1', '1 year'), ('2', '2 years')], db_column='cycle_prepa', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='utilsdata',
            name='filiere',
            field=models.CharField(blank=True, choices=[(None, ''), ('GM', 'Genie Mecanique'), ('GEM', 'Genie Electromecanique'), ('IAGI', 'Genie Informatique'), ('GI', 'Genie Industrielle'), ('MSEI', 'Genie Electrique')], db_column='filiere', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='utilsdata',
            name='image',
            field=models.FileField(db_column='image_path',upload_to=FaceRecoApp.models.upload_location),
        ),
        migrations.AlterField(
            model_name='utilsdata',
            name='module_name',
            field=models.CharField(db_column='module', max_length=400),
        ),
    ]
