# Generated by Django 5.0.3 on 2024-04-12 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecoApp', '0005_utilsdata_section_alter_utilsdata_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='student_class',
        ),
        migrations.AlterField(
            model_name='students',
            name='student_class',
            field=models.ForeignKey(db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_students', to='FaceRecoApp.class'),
        ),
        migrations.AddField(
            model_name='module',
            name='student_class',
            field=models.ManyToManyField(db_column='class_id', null=True, related_name='module_class', to='FaceRecoApp.class'),
        ),
    ]
