# Generated by Django 5.0.3 on 2024-04-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecoApp', '0006_remove_module_student_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='student_class',
            field=models.ManyToManyField(db_column='class_id', related_name='module_class', to='FaceRecoApp.class'),
        ),
    ]
