# Generated by Django 5.0.3 on 2024-04-12 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecoApp', '0007_alter_module_student_class'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='utilsdata',
            table='seancedata',
        ),
    ]
