# Generated by Django 5.0.3 on 2024-04-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecoApp', '0010_alter_utilsdata_cycle_eng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilsdata',
            name='cycle_eng',
            field=models.CharField(blank=True, choices=[(None, ''), ('1', '1 year'), ('2', '2 years'), ('3', '3 years')], db_column='cycle_eng', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='utilsdata',
            name='cycle_prepa',
            field=models.CharField(blank=True, choices=[(None, ''), ('1', '1 year'), ('2', '2 years')], db_column='cycle_prepa', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='utilsdata',
            name='filiere',
            field=models.CharField(blank=True, choices=[(None, ''), ('GM', 'Genie Mecanique'), ('GEM', 'Genie Electromecanique'), ('IAGI', 'Genie Informatique'), ('GI', 'Genie Industrielle'), ('MSEI', 'Genie Electrique')], db_column='filiere', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='utilsdata',
            name='module_name',
            field=models.CharField(choices=[(None, '')], db_column='module', max_length=400),
        ),
        migrations.AlterField(
            model_name='utilsdata',
            name='section',
            field=models.CharField(blank=True, choices=[(None, ''), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], db_column='section', max_length=80, null=True),
        ),
    ]
