# Generated by Django 5.0.6 on 2024-06-23 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("FaceRecoApp", "0012_alter_utilsdata_cycle_alter_utilsdata_module_name"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="teachers",
            table="teacher",
        ),
    ]
