# Generated by Django 5.0.3 on 2024-03-17 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('cycle', models.TextField()),
                ('cycle_year', models.IntegerField()),
                ('filiere', models.TextField()),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.TextField()),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.TextField()),
                ('student_class', models.ForeignKey(db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='face_recognizer.class')),
                ('teacher', models.ForeignKey(db_column='teacher_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='face_recognizer.teachers')),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('seance_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_hour', models.IntegerField()),
                ('end_hour', models.IntegerField()),
                ('week_day', models.CharField(max_length=10)),
                ('full_date', models.DateField()),
                ('module', models.ForeignKey(db_column='module_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='face_recognizer.module')),
                ('student_class', models.ForeignKey(db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='face_recognizer.class')),
            ],
            options={
                'db_table': 'seance',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.TextField()),
                ('student_class', models.ForeignKey(db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='face_recognizer.class')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('presence_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=False)),
                ('seance', models.ForeignKey(db_column='seance_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='face_recognizer.seance')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='face_recognizer.students')),
            ],
            options={
                'db_table': 'presences',
            },
        ),
    ]
