# Generated by Django 5.0.3 on 2024-04-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=256, null=True)),
                ('firstName', models.CharField(db_column='firstName', max_length=256, null=True)),
                ('email', models.EmailField(max_length=150)),
                ('subject', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
