# Generated by Django 5.0.6 on 2024-06-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("face_recognizer", "0011_alter_utilsdata_cycle_eng_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilsdata",
            name="cycle",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("cycle_preparatoire", "Preparatory Cycle"),
                    ("cycle_ingenieur", "Engineering Cycle"),
                ],
                db_column="cycle",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="utilsdata",
            name="module_name",
            field=models.CharField(db_column="module", max_length=400),
        ),
    ]
